### ISSUE TITLE
seq(from, to, numberOfPoints) 

### ISSUE THREAD

**Issue by arcolombo** [coatless/r-to-armadillo#1]
Here is a handy function that doesn't restrict itself to integers,  but is very similar to the R `base::seq` function, which is `seq(from, to, numberofPoints)`.  In this case,  this is used to create sequences  from -`x0`  to `x1`  by `2*x0/(numberofPoints)`

``` cpp
arma::vec seq_cpp(double a, double np){
  double inc  = (2*a)/np;

  arma::vec s(np);

  for(unsigned int i = 0; i < np; i++){
    s(i) = -a + i*inc;
  }

  return s;
}
```

**Comment by arcolombo** [comment]
If it is preferable to submit a formal  Pull Request,  then I could....

**Comment by coatless** [comment]
Hi @arcolombo, please do so! This will be a great addition. Thanks.

**Comment by arcolombo** [comment]
ok to close this out.

**Comment by arcolombo** [comment]
I'm honestly way too lazy to send a pull request, but here it is with armadillo library

```
arma::vec seq_by(long double a, long double np){

arma::vec s(np);
s = arma::linspace(-a,a,np); 


  return s;
  }
```

**Comment by arcolombo** [comment]
prolly not even needed after reading through Arma docs...

**Comment by coatless** [comment]
@arcolombo

You would be amazed.

This is actual a great example of using [linspace](http://arma.sourceforge.net/docs.html#linspace) in [Armadillo's API](http://arma.sourceforge.net/docs.html#linspace).

I'll bring it into the `seq` set of functions later today. Thanks again!
